version: 0.2

phases:
  pre_build:
    commands:
      - npm ci
      - rm -r node_modules/terser
      - aws --version
      - npm install terser@3.14.1 --save-dev
      # - command
  build:
    commands:
      - npm run build:preprod
  post_build:
    commands:
      - echo Emptying website bucket for new updation
      - echo Bucket is empty now

artifacts:
  files:
    - '**/*'

  discard-paths: no
  base-directory: build
